Feature/migrate room database
Knock-Lock/Knock-Lock pull request #101
Opened 2023-03-08 11:14 UTC by 014967

## 미완

## 🔥 관련 이슈

## 🔥 PR Point

## 📷 Screenshot

2023-03-08 15:17 UTC, KimHance reviewed
마이그레이션... 양이 어마어마하네요 고생하셨습니다!!👍

2023-03-08 15:17 UTC, KimHance commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
room에 접근할 때 자동으로 IO디스패처로 설정되어 따로 할 필요가 없지 않나요??

2023-03-08 15:17 UTC, KimHance commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +        }.flowOn(Dispatchers.IO)
디스패처 확인 부탁드립니다 ~

2023-03-08 15:17 UTC, KimHance commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        }.flowOn(Dispatchers.IO)
Redispatching 할 필요가 없어보입니다!

2023-03-08 15:17 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                        SimpleDateFormat("a HH:mm", Locale.KOREA).format(date)
util 패키지에 TimeFormat을 만들어놨는데 이용해보면 어떠시나용??

2023-03-08 15:17 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            }
코드를 정확히 이해못해서 질문합니당.
notification별로 각각 job을 생성하는 형태인데 의도한게 맞나요??

2023-03-08 15:17 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            }
또 궁금한게 notificationScope가 어느정도의 스코프가 될지 알 수 있을까요?
스코프가 크다면 notification 별로 생기는 job은 알람이 많으면 매우 증가하지 않을까요??

@jaeryo2357  어떻게 생각하시나용? 제가 파악한게 맞을까요?

2023-03-08 15:19 UTC, KimHance commented on data/src/main/java/com/knocklock/data/di/RepositoryModule.kt
> +    ): NotificationRepository
궁금해서 의견을 듣고 싶은데
notificationRepo가 혹시 Service쪽 이외에 의존성을 갖는곳이 있을까요??
없다면 ServiceScope도 괜찮아 보이는데

다들 의견이 궁금합니당
@jaeryo2357 @014967

2023-03-09 08:00 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
맞아영 수정할께여

2023-03-09 08:08 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            }
의도 된게 맞구 notification별 insert를 병렬처리해주려고했어요

2023-03-09 08:40 UTC, 014967 commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +        }.flowOn(Dispatchers.IO)
@KimHance suspend keyword가 붙은 Room Function은 Dispatcher를 안붙여도 되는 것으로 알고 있는데 ,반환타입이 Flow인 경우도 동일한가요? Thread찍어보니까 아닌것 같아서 궁금하네영

2023-03-09 13:08 UTC, KimHance commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +        }.flowOn(Dispatchers.IO)
확인했습니다!

2023-03-09 13:27 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            }
job cancel 추가

2023-03-10 07:44 UTC, 014967 commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +        }.flowOn(Dispatchers.IO)
@KimHance [2b32e10](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/2b32e102b072f0329518f5d99f6258b71268eb44) 이동했습니다~

2023-03-13 05:53 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            }
@KimHance [bce560d](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/bce560dd229ddd59b1cd4d7a0c175862214ba7bb) 추가했습니당

2023-03-13 06:08 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                        SimpleDateFormat("a HH:mm", Locale.KOREA).format(date)
@KimHance [0e2c982](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/0e2c982222f7cc87c07ca63d372f5a6413d1d54d) 새롭게 추가했습니다

2023-03-13 06:10 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
@KimHance [2b32e10](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/2b32e102b072f0329518f5d99f6258b71268eb44) 제거했습니다

2023-03-13 10:08 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        }.flowOn(Dispatchers.IO)
```kotlin
@JvmStatic
fun createFlow(db: RoomDatabase, inTransaction: Boolean, tableNames: Array, callable: Callable): Flow<@JvmSuppressWildcards R> =
    flow {     // Observer channel receives signals from the invalidation tracker to emit queries.
        val observerChannel = Channel(Channel.CONFLATED)
        val observer = object : InvalidationTracker.Observer(tableNames) {
            override fun onInvalidated(tables: MutableSet) {
                observerChannel.offer(Unit)
            }
        }
        observerChannel.offer(Unit) // Initial signal to perform first query.
        val flowContext = coroutineContext
        val queryContext = if (inTransaction)
                db.transactionDispatcher
            else
                db.queryDispatcher
        withContext(queryContext) {
            db.invalidationTracker.addObserver(observer)
            try {
                // Iterate until cancelled, transforming observer signals to query results to
                // be emitted to the flow.
                for (signal in observerChannel) {
                    val result = callable.call()
                    withContext(flowContext) { emit(result) }
                }
            } finally {
                db.invalidationTracker.removeObserver(observer)
            }
        }
    }
```

room 생성되는 코드 보니까 내부적으로 io Thread를 하고 있어서 제거해도 될 것 같아요!

2023-03-13 10:41 UTC, jaeryo2357 requested changes
어려운 기능 인데.. 얼른 이슈 해결되고 해피엔딩 되었으면 좋겠네요
수고많았어요!

2023-03-13 10:41 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        }.flowOn(Dispatchers.IO)
```kotlin
@JvmStatic
fun createFlow(db: RoomDatabase, inTransaction: Boolean, tableNames: Array, callable: Callable): Flow<@JvmSuppressWildcards R> =
    flow {     // Observer channel receives signals from the invalidation tracker to emit queries.
        val observerChannel = Channel(Channel.CONFLATED)
        val observer = object : InvalidationTracker.Observer(tableNames) {
            override fun onInvalidated(tables: MutableSet) {
                observerChannel.offer(Unit)
            }
        }
        observerChannel.offer(Unit) // Initial signal to perform first query.
        val flowContext = coroutineContext
        val queryContext = if (inTransaction)
                db.transactionDispatcher
            else
                db.queryDispatcher
        withContext(queryContext) {
            db.invalidationTracker.addObserver(observer)
            try {
                // Iterate until cancelled, transforming observer signals to query results to
                // be emitted to the flow.
                for (signal in observerChannel) {
                    val result = callable.call()
                    withContext(flowContext) { emit(result) }
                }
            } finally {
                db.invalidationTracker.removeObserver(observer)
            }
        }
    }
```

room 생성되는 코드 보니까 내부적으로 io Thread를 하고 있어서 제거해도 될 것 같아요!

2023-03-13 10:41 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        }.flowOn(Dispatchers.IO)
```suggestion
 return groupDao.getGroupWithNotifications().map { groupWithNotifications ->
            groupWithNotifications.filter {
                it.notifications.isNotEmpty()
            }.map { groupWithNotification ->
                val notifications =
                    groupWithNotification.notifications.sortedByDescending { it.postedTime }
                groupWithNotification.copy(
                    notifications = notifications
                ).toModel()
            }.sortedByDescending { it.notifications[0].postedTime }
        }.flowOn(Dispatchers.IO)
```

flow 빌더를 새로 생성안하고  map으로 바꿔줘도 될 것 같아요 :)

2023-03-13 10:41 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +        "DELETE FROM `GROUP` WHERE `key` Like :key"
Sql 전문가는 아니지만? ㅋㅋㅋㅋ Like보다는 =을 사용하는건 어떤가요?

조회는 예를 들어 데이터베이스 관리자가 아니어도 관련 직군들이 데이터 통계를 내기 위해서 `Like`를 많이 사용하는 걸로 알고있어요.  정확히 일치하지 않는 단어라도 비슷한 결과들을 모아 통계내기 좋아서

그런데 데이터를 삭제하는 중요한 행동의 경우에는 like 보다는 equlas 비교가 좋을 것 같아요!

key가 나중에 언제 변경될지 모르고 패턴? 구조도 변경될 수도 있고 Like를 하다보면 삭제해야하지 말아야 할 또 다른 row가 지워질 수 있는 최악의 케이스가 있기 때문이에요. 데이터 무결성을 생각하면 key가 정확히 동일한 값일때 지워주는게 좋을 것 같아서요 :)

다른 Delete 하는 Dao도 한번 확인해주세요!

2023-03-13 10:41 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/source/local/notification/entity/Notification.kt
> + */
친절한 주석 감사합니다 :)

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
>      }
너무 좋네요! 코드를 다시 보니까 `derivedStateOf`의 역할이 떠올랐어요. 값이 변경되는 시점에만 recomposition이 진행된다 맞죠!?

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +        updateTransitionState(fraction)
이 부분은 기존 코드를 유지하려면 true 일때만 호출하지 않고 false일 때도 불러줘야 할 것 같은데 맞을까요? 흠 이렇게하면 변경된 의미가 없게 되는 걸까요 fraction 변수를 넘겨줌으로 skip이 recomposition 시에 skip이 될 것 같은데요

```suggestion
     updateTransitionState(fraction)
```

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +            key = { item: GroupWithNotification -> item.group.key }
매번 생성하지 않고 model 자체에 들고 있게 변경된 점 좋네요!

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +    val temp = getDrawableAndAppTitle(packageManager, packageName)
```suggestion
    val (title, icon) = getDrawableAndAppTitle(packageManager, packageName)
```
Pair를 위처럼 받을 수 있어요. 가독성 🆙

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +    return statusBarNotifications.asSequence().filter { it.toModel(packageManager) != null }.map { it.toModel(packageManager)!! }.toList().toTypedArray()
toModel 연산이 2번 될 것 같아요! !!도 지울 수 있겠네요 :)
```suggestion
    return statusBarNotifications.asSequence().map{ it.toModel(packageManager) }.filter { it != null }.toList().toTypedArray()
```

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +        if (subText == "")getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
```suggestion
        if (subText == "") getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
```
:)

2023-03-13 10:41 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +        if (subText == "")getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
"" 비교는 isEmpty extensions을 쓰면 더 가독성이 좋을 것 같아요!

```suggestion
    return if (title.isNotEmpty() || content.isNotEmpty()) {
        val appTitle = getDrawableAndAppTitle(packageManager, packageName).first ?: ""
        val subText: String = convertString(this.notification.extras.getCharSequence("android.subText"))

        if (subText.isEmpty) getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
```

2023-03-13 12:55 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        }.flowOn(Dispatchers.IO)
@jaeryo2357 Room은 transacitonDispatcher를 사용하는 군영

2023-03-13 14:25 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +        if (subText == "")getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
꼼꼼스.. ㄷ

2023-03-13 14:26 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +        if (subText == "")getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
동의합니다 ㅎㅎ

2023-03-13 14:28 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/util/TimeFormat.kt
> +}
하하핳 좋아용~

2023-03-13 14:32 UTC, KimHance requested changes
민욱이형이 먼저 깔끔하게 리뷰해주셔서 딱히 따로는 없는것 같습니다

2023-03-14 05:29 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +        if (subText == "")getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
@jaeryo2357 @KimHance [b4f68e1](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/b4f68e10bbc60762f74fede162e832aaa76f6b33) 수정했습니당

2023-03-14 05:29 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +        if (subText == "")getGroupKey(packageName, appTitle, title) else getGroupKey(packageName, appTitle, subText)
@jaeryo2357 @KimHance [b4f68e1](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/b4f68e10bbc60762f74fede162e832aaa76f6b33) 수정했습니다

2023-03-14 05:30 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +    return statusBarNotifications.asSequence().filter { it.toModel(packageManager) != null }.map { it.toModel(packageManager)!! }.toList().toTypedArray()
@jaeryo2357 [b4f68e1](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/b4f68e10bbc60762f74fede162e832aaa76f6b33)
Sequence라 mapping전 filter를 해주는게 좋아서, 기존 filter에서 model mapping되는 로직을 필터와 분리했습니다

2023-03-14 05:31 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +        }.flowOn(Dispatchers.IO)
@jaeryo2357 [2637723](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/26377234f96f3fbe74fbc4a853cd72c556c33722) 수정했습니당

2023-03-14 05:32 UTC, 014967 commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +        "DELETE FROM `GROUP` WHERE `key` Like :key"
@jaeryo2357 [1172f72](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/1172f7252574f3b76f0c736ef5792f089f150f1f) 수정했습니당 동일값으로 지우는게 좋네영

2023-03-14 06:04 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +        updateTransitionState(fraction)
@jaeryo2357 맞네영 fraction이 false일때도 불러줘야해요 !!

2023-03-14 06:21 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +        updateTransitionState(fraction)
@jaeryo2357 하지만 다음에 성능 문제를 해결하기 위해서 조금 코드를 축소화하려고합니다.[b16aa67](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/b16aa67e10fbb03b8988035f167fea8c7a1d50f2) 당장은 필요가 없을꺼같아서 제거하도록 하겠습니다

2023-03-14 06:22 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/mapper/NotificationMapper.kt
> +    val temp = getDrawableAndAppTitle(packageManager, packageName)
@jaeryo2357 [b4f68e1](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/b4f68e10bbc60762f74fede162e832aaa76f6b33) 수정했습니다

2023-03-14 09:36 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
>      }
@jaeryo2357 성능 문제를 해결하기 위해서 조금 코드를 축소화하려고합니다.[b16aa67](https://github.com/Knock-Lock/Knock-Lock/pull/101/commits/b16aa67e10fbb03b8988035f167fea8c7a1d50f2) 당장은 필요가 없을꺼같아서 제거하도록 하겠습니다

2023-03-14 10:27 UTC, jaeryo2357 approved these changes
확인했어요! 수고많았어요 :)

2023-03-14 15:08 UTC, KimHance reviewed
줄 개행 저것만 확인해 주세용

2023-03-14 15:08 UTC, KimHance commented on data/src/main/java/com/knocklock/data/source/local/notification/dao/GroupDao.kt
> +    )
Reformat code가 이렇게 된건가용??

2023-03-14 16:52 UTC, merged