[feat]: credit 텍스트에 링크걸기
Knock-Lock/Knock-Lock pull request #106
Opened 2023-03-21 15:41 UTC by KimHance

## 🔥 관련 이슈

close #98

## 🔥 PR Point

- 크레딧 텍스트 링크

## 📷 Screenshot
https://user-images.githubusercontent.com/86879099/226659128-f207fe4e-ab16-4940-98c5-e1926dd51706.mov

2023-03-21 15:41 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/MainActivity.kt
> +        const val KNOCK_LOCK_EMAIL_ADDRESS = "rldkvos2@gmail.com"
계좌는 매쉬업13기 모임통장이고
이메일은 제꺼 임시로 설정했습니당

2023-03-21 15:43 UTC, KimHance commented
라이선스랑 이용약관은 정확히 어떻게 해야할지 몰라서 임시로 깃헙으로 연결해 놓았습니다.
후에 배포가 되면 "평가하기"가 들어가고 후기작성으로 이동시킬 계획이에용

2023-03-22 12:46 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/MainActivity.kt
> +        const val KNOCK_LOCK_EMAIL_ADDRESS = "rldkvos2@gmail.com"
ㅋㅋㅋㅋㅋ 좋네여

2023-03-22 15:07 UTC, jaeryo2357 requested changes
수고했어요~~!! 후원 많이 쌓이면 좋겠네요

2023-03-22 15:07 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
> +                            context.startActivity(intent)
나중에 노션에 개인정보처리방침 만들고 링크를 걸어도 좋을 것 같아요!

2023-03-22 15:07 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/setting/credit/CreditScreen.kt
> +        listOf(
👍 좋네용
좀 더 개인적인 욕심으로는 Enum으로 관리해도 좋을 것 같아요. 이 부분은 참고만 해주세요

2023-03-22 15:07 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
> +                            }
에뮬레이터에서 적절한 메일 앱이 없어서 클릭해도 아무 동작이 없네요.
query 명시를 안해서 그런가 했더니 아니더라구요.

공식 문서를 보니까 아래 코드처럼 구현하면 적절한 앱이 없다는 것도 UI로 표시되어서 좋은 것 같아요!
```suggestion
                             val intent = Intent(Intent.ACTION_SENDTO).apply {
                                data = Uri.parse("mailto:")
                                putExtra(Intent.EXTRA_EMAIL, arrayOf(KNOCK_LOCK_EMAIL_ADDRESS))
                            }
                            context.startActivity(Intent.createChooser(intent, null))
```

![image](https://user-images.githubusercontent.com/33657541/226948065-0078a576-cdf5-4494-84ef-0b705277b32e.png)

2023-03-23 13:28 UTC, 014967 approved these changes

2023-03-23 13:51 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/setting/credit/CreditScreen.kt
> +        listOf(
참고는 곧 적용입니다,

2023-03-23 14:43 UTC, jaeryo2357 approved these changes
확인했어요~~!

2023-03-30 12:03 UTC, merged