PhotoPicker & Crop Iibrary 적용
Knock-Lock/Knock-Lock pull request #177
Opened 2023-07-24 11:23 UTC by 014967

## 🔥 관련 이슈

## 🔥 PR Point
- Crop library 적용해보았습니다.
- PhotoPicker를 적용하였습니다. 
- File Path를 사용해서, 배경화면을 설정에서 변경할 때마다 file을 생성하고, save를 누를시에 
save되는 file이름과 다른 모든 파일을 제거하도록 하였습니다.

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|이미지 크롭 및 포토피커|https://github.com/Knock-Lock/Knock-Lock/assets/62296097/2ac40f42-c863-4278-b6bb-8fa28047a62e|
|...||

2023-07-26 15:47 UTC, jaeryo2357 requested changes
확인했어요!

2023-07-26 15:47 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                val uri = Uri.parse((value.screen.background as LockScreenBackground.LocalImage).imageUri)
```suggestion
                val uri = Uri.parse((value.screen.background as?LockScreenBackground.LocalImage).imageUri)
```

타입 캐스팅 안정성을 위해 as?를 사용하는게 좋겠어요! 항상 LocalImage 인 것이 보장이 안될 것 같아요 (추후 타입추가 고려)

2023-07-26 15:47 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                    return@launch
```suggestion
                if (uri?.path == null) {
                    return@launch
```

현재 코드에서 uri이 플랫폼타입이어서 NullCheck 해주는 것이 안전해요

2023-07-26 15:47 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                    }
```suggestion
                    val specificFile = File(uri.path ?: return@launch)
                    context.filesDir.listFiles()?.forEach { file ->
                        if (file.name != specificFile.name) {
                            if (file.delete()) {
                                Log.d("HomeViewModel-File", "제거 성공")
                            } else {
                                Log.d("HomeViewModel-File", "$file 제거 실패")
                            }
                        }
                    }
```

위처럼 변경하면 어때요??

1) index 관리 필요 x
2) println은 릴리즈모드에서도 그래로 노출됨

2023-07-26 16:42 UTC, KimHance reviewed
포로피커라니.. ㄷㄷ PTSD가 오는군요

2023-07-26 16:42 UTC, KimHance commented on presentation/src/main/AndroidManifest.xml
> +
혹시 모르니 자동 백포팅 모듈 추가하는게 어떨까용 

https://developer.android.com/training/data-storage/shared/photopicker?hl=ko

![image](https://github.com/Knock-Lock/Knock-Lock/assets/86879099/770cbf76-e441-4c20-aac5-3f058fb2050e)

2023-07-26 16:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/home/HomeRoute.kt
>              }
![image](https://github.com/Knock-Lock/Knock-Lock/assets/86879099/e0f26e56-795e-4e49-8bdd-973ca9098aaa)
이렇게 제공하고 있는데 백그라운드가 베이스로 깔린 앱이라 좀 무섭긴 하네요 ㅎㅎ..

+@ 참고로 API 30미만은 저 퍼미션을 사용하면 안되서 분기가 필요합니다

2023-07-26 16:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/home/HomeRoute.kt
>              }
현재 방식은 사진 선택할 때마다 새로 파일이 만들어지는거 같은데, 해당 이미지 파일을 바로 접근하는 방법은 안됬었나용??

물론 해당 이미지 파일을 접근하려면 여러 귀찮은 작업이 포함되어야 합니다ㅠㅠ
+ PhotoPicker가 사용가는하지 여부
+ uri 타입에 따른 query 분기 처리
+ 기존 파일 선택기로 선택된 uri의 경우 ColumnIndex를 접근하기위해 uri 1차 변형 및 가공 필요
+ uri 로 쿼리 가능한지 여부 판단        
+ 기타 등등..?

이렇게 해당 uri 에서 path를 뽑아내서(permission less 한 uri라서 직접 파일접근 불가능) 파일에 접근해 작업을 이어갈 수 있습니다

2023-07-27 12:15 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                    return@launch
java꺼라서 플랫폼타입이기 때문에 kotlin으로 변환해서 null check

2023-07-27 12:18 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeRoute.kt
>      val context = LocalContext.current
null check한번 ㄱㄱ

2023-07-27 12:22 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeRoute.kt
> +        rememberLauncherForActivityResult(ActivityResultContracts.PickVisualMedia()) { photoUri ->
여기다가 추가하기

2023-07-27 12:23 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                val uri = Uri.parse((value.screen.background as LockScreenBackground.LocalImage).imageUri)
@jaeryo2357 반영할께영

2023-07-27 12:23 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                    }
@jaeryo2357 야무지게 간결해졌당 ㅎ

2023-07-27 12:25 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                    }
이거로 반영할꼐영

2023-07-28 07:49 UTC, 014967 commented on presentation/src/main/AndroidManifest.xml
> +
@KimHance [2803eb8](https://github.com/Knock-Lock/Knock-Lock/pull/177/commits/2803eb8ae8593cc78a4a90f668647d3a471c3bad)반영했어용

2023-07-28 07:49 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +                    }
@jaeryo2357 [c977b31](https://github.com/Knock-Lock/Knock-Lock/pull/177/commits/c977b313275e9f46ec65a27ef324e2ccb41d9a33) 반영했어용

2023-07-28 08:22 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeRoute.kt
>      val context = LocalContext.current
[e9729cf](https://github.com/Knock-Lock/Knock-Lock/pull/177/commits/e9729cf07cc68d38a79c25f393bd18e33401d5ec)

2023-07-28 09:21 UTC, merged