Feature/create notification listener
Knock-Lock/Knock-Lock pull request #45
Opened 2022-12-07 07:54 UTC by 014967

## 🔥 관련 이슈

close #25 

## 🔥 PR Point
*  NotificationListener구현
         - Database에 Notification 저장

*  Notification 저장, 삭제, 가져오기 로직 구현
        -   AppDatabase 생성
        -   Repository, Datasource, Dao생성
        -   Insert, Select, DeleteAll ,DeleteById 로직 추가

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|NotificationListener 구현 및 Composable에 보여주기|![KakaoTalk_Video_2022-12-07-16-44-06](https://user-images.githubusercontent.com/62296097/206119253-72ab87b9-a19f-45d6-8259-6ff6c1689d3d.gif)|

2022-12-07 13:56 UTC, jaeryo2357 requested changes
오 알람을 이렇게 받아올 수 있군요 :)

2022-12-07 13:56 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/mapper/EntityMapper.kt
> +)
EMPTY.copy로 하는 이유 있을까요??
저는 EMPTY는 test 용도로 사용되는 Mock 변수인줄 알았거든요! 👁️

2022-12-07 13:56 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenUiState.kt
> +    data class Success(val notificationList: List<Notification>) : NotificationUiState()
```suggestion
    object Empty: NotificationUiState()
    data class Success(val notificationList: List<Notification>) : NotificationUiState()
```

init 보다는 Empty로 rename하는건 어떤가요? 😄

2022-12-07 13:56 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotificationListener.kt
> +import com.knocklock.domain.model.Notification as NotificationDomainModel
오 👍

2022-12-07 13:56 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotificationListener.kt
> +        notificationRepository = NotificationRepositoryImpl(this) // data layer 의존성 제거 hilt로
```suggestion
       //TODO: data layer 의존성 제거 hilt로
        notificationRepository = NotificationRepositoryImpl(this)
```

TODO 주석으로 해도 좋을 것 같아요. 이렇게 해두면 IDE에서 TODO 주석만 찾을 수 있어요!

2022-12-07 13:56 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotificationListener.kt
> +    override fun onNotificationPosted(sbn: StatusBarNotification?) {
오.. 이 함수로 알림이 오는군요

2022-12-07 13:56 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotificationListener.kt
> +        super.onNotificationRemoved(sbn)
여기서 룸 지워주는 기능을 추가해도 좋곘네요! 다음 Step에 진행해도 좋을 것 같아요

2022-12-07 13:56 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +                }
Notification List라는 Composable로 분리해도 좋을 것 같아요!

2022-12-07 13:56 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +            }
flow로 한번 감싼 이유가 있을가요?? 혹시 데이터를 못받는 에러와 관련있을까요?
```suggestion
        return notificationLocalDataSource.getNotificationList().map { it.toModel }
```

2022-12-07 14:35 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotificationListener.kt
> +        super.onNotificationRemoved(sbn)
@jaeryo2357 보니까 알림 지워지면 삭제해도 될꺼같네영!!

2022-12-07 14:42 UTC, KimHance approved these changes
컴포즈는 어렵네요 ㅎ..
멋집니당 ^^

2022-12-07 14:42 UTC, KimHance commented on data/src/main/java/com/knocklock/data/mapper/EntityMapper.kt
> +)
저도 EMPTY.copy로 하는 이유가 궁금합니다.

2022-12-07 14:42 UTC, KimHance commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +            }
저도 Flow.map 써도 될것 같아요!

2022-12-07 14:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenViewModel.kt
> +    }
나중이겠지만 알람 지우기 버튼이 만들어지면  private 지정자를 빼게 되나요??

2022-12-08 06:26 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenViewModel.kt
> +    }
@KimHance 현재는 테스트용이라 실행할 때 마다 쌓여서 삭제해주는 로직을 넣어줬는데 현수님 말대로 나중에는 지정자를 수정하게 될 예정입니다

2022-12-08 07:32 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenUiState.kt
> +    data class Success(val notificationList: List<Notification>) : NotificationUiState()
@jaeryo2357 좋습니당

2022-12-08 07:32 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotificationListener.kt
> +        notificationRepository = NotificationRepositoryImpl(this) // data layer 의존성 제거 hilt로
@jaeryo2357 주석 반영할께용

2022-12-08 09:11 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +            }
```kotlin
return notificationLocalDataSource.getNotificationList().map { notificationEntityList ->
            notificationEntityList.map {
                it.toModel()
            }
        }
```

로했을때 데이터가 2개씩 반환이 되네영

2022-12-08 09:16 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +                }
네 그게 좋을 것같아용

2022-12-09 04:00 UTC, 014967 commented on data/src/main/java/com/knocklock/data/mapper/EntityMapper.kt
> +)
습관이였는데, 장점을 찾지 못해서 제거했습니당

2022-12-09 04:00 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +            }
@jaeryo2357  오류였던것으로 정상작동확인했습니다

2022-12-09 04:00 UTC, 014967 commented on data/src/main/java/com/knocklock/data/repository/NotificationRepositoryImpl.kt
> +            }
@KimHance 반영했습니당

2022-12-09 06:56 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
>          modifier = modifier,
@jaeryo2357  @KimHance 
LockScreenNotifcationListColumn을 stable하게 바꿔서 skippable이 가능하도록 변경하였습니다

2022-12-09 06:57 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
>  data class Notification(
@jaeryo2357  @KimHance 
Notification이 unstable한 data class 이기때문에 Immutable annotation으로 stable하게 변경하였습니다.

2022-12-09 11:16 UTC, jaeryo2357 approved these changes
👍

2022-12-09 11:16 UTC, merged