[feat]: #14 setting lock type
Knock-Lock/Knock-Lock pull request #58
Opened 2022-12-14 13:01 UTC by KimHance

## 🔥 관련 이슈

close #14 

## 🔥 PR Point

- 활성화 스위치 변경에 따른 잠금 타입 변경

2022-12-14 15:04 UTC, jaeryo2357 requested changes
수고하셨어요 :)  LGTM

2022-12-14 15:04 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/UserRepositoryImpl.kt
> +    private val userDataStore: DataStore<UserPreference>,
```suggestion
    private val userDataStore: DataStore<UserPreference>
```
, 지워주세요! :)

2022-12-14 15:04 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/UserRepositoryImpl.kt
> +    }
추후 Auth 타입 추가되는 것을 고려해서 `AuthenticationType`을 넘기는 것이 좋을 것 같은데 어떻게 생각하시나요?
이렇게 되면 domain -> data model로 변경되는 mapper 함수가 필요하겠네요 🧑‍🦱 

```suggestion
    override suspend fun changeMode(authenticationType: AuthenticationType) {
        userDataStore.updateData { userPreference ->
              userPreference.copy(authenticationType = authenticationType)
        }
    }
```

2022-12-14 15:04 UTC, jaeryo2357 commented on domain/src/main/java/com/knocklock/domain/usecase/setting/GetUserTypeUseCase.kt
> +}
Type은 빼도 될것 같네요?? 👁️ 
```suggestion
class GetUserUseCase @Inject constructor(
    private val userRepository: UserRepository
) {
    operator fun invoke() = userRepository.getUser()
}
```

2022-12-14 15:04 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/SettingViewModel.kt
> +    }
```suggestion
    val userSetting = getUserTypeUseCase().map { userInfo ->
        UserSetting(isPasswordActivated = userInfo.authenticationType == AuthenticationType.PASSWORD)
    }
```

이렇게 표현하는 것은 어떤가요?

2022-12-14 15:41 UTC, KimHance commented on data/src/main/java/com/knocklock/data/repository/UserRepositoryImpl.kt
> +    }
현재 비밀번호 유무만 존재하기 때문에 boolean 값을 넘겨줬는데 추후에 pin이나 패턴같은게 추가되는걸 고려하자는 거겠죠??

2022-12-14 15:41 UTC, KimHance commented on domain/src/main/java/com/knocklock/domain/usecase/setting/GetUserTypeUseCase.kt
> +}
찬성입니다~

2022-12-14 15:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/SettingViewModel.kt
> +    }
더 짧고 간결하네용 좋습니다 ㅎㅎ

2022-12-14 16:13 UTC, jaeryo2357 commented on data/src/main/java/com/knocklock/data/repository/UserRepositoryImpl.kt
> +    }
맞아요!

2022-12-15 06:42 UTC, 014967 approved these changes
민욱이가 이야기 하는 확장성 이외에 다른 부분은 문제없어보입니다 고생했어용

2022-12-16 13:26 UTC, 014967 approved these changes

2022-12-16 15:52 UTC, jaeryo2357 approved these changes
수고했어용!@!

2022-12-16 15:57 UTC, merged