[feat]: #63 setting navigation
Knock-Lock/Knock-Lock pull request #65
Opened 2022-12-21 09:53 UTC by KimHance

## 🔥 관련 이슈

close #63 

## 🔥 PR Point

- 세팅화면 네비게이션 연결

2022-12-21 09:54 UTC, KimHance commented
컴포즈 네비게이션 익숙치가 않아서 맞는지 헷갈리네요 ㅎㅎ..

2022-12-21 12:44 UTC, jaeryo2357 requested changes
수고했어요 :)

2022-12-21 12:44 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/SettingNavHost.kt
> +    ) {
이름이 SettingNavHost로 되어 있어서 중첩 NavGraph를 구성하고 싶은 것처럼 보여요!
그럴 때는 NavHost 내부에  `navigation` 확장함수로 중첩 NavGraph를 구성하는 것 같아요!
https://developer.android.com/jetpack/compose/navigation

2022-12-21 12:44 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/menu/Menu.kt
> +            text = stringResource(titleRes),
titleRes로 구분했군요 👍

2022-12-22 05:21 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/SettingNavHost.kt
> +    ) {
```kotlin
fun NavGraphBuilder.settingGraph(
    navController : NavController
) {
    navigation(
        route = NavigationRoute.SettingScreenGraph.route,
        startDestination = NavigationRoute.SettingScreenGraph.SettingScreen.route
    ) {
        composable(
            route = NavigationRoute.SettingScreenGraph.SettingScreen.route
        ) {
        }
        composable(
            route = NavigationRoute.SettingScreenGraph.PasswordScreen.route
        ) {
        }
    }
}
```
위와 같이 구현을 한다면 

```kotlin
Scaffold(){

 NavHost(
                    modifier = Modifier.padding(paddingValues),
                    startDestination = NavigationRoute.SettingScreenGraph.route
                ) {
                    homeGraph(
                    )
                    settingGraph(
                    )
                    000Graph(
                    )
                    000Graph(
                    )
                }
}
```
위와 같이 구성할 수 있겠네용

2022-12-22 05:26 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/SettingNavHost.kt
> +    ) {
이런 그래프나 topbar , bottombar, navigation를 관리해주기 위해서 xxxApp등의 최상단 컴포저블과 AppState stateholder를 만들고는 하는거같아용(물론 우리는 bottomBar는 없지만)

2022-12-22 07:12 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/menu/Menu.kt
> +            text = stringResource(titleRes),
string으로 비교하자니 코드가 이쁘지 않아서 리소스로 바꿨습니당 ^^

2022-12-22 07:13 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/ui/setting/SettingNavHost.kt
> +    ) {
숙지가 좀더 필요했던 부분이군요.. 감사합니다~~ ^오^

2022-12-22 13:32 UTC, 014967 approved these changes

2022-12-22 13:36 UTC, jaeryo2357 approved these changes
👍

2022-12-22 13:37 UTC, merged