[feat]: #56 setting password by condition
Knock-Lock/Knock-Lock pull request #67
Opened 2022-12-28 07:50 UTC by KimHance

## 🔥 관련 이슈

close #56 

## 🔥 PR Point

- 비밀번호 활성화 시 비밀번호 존재 여부에 따른 분기
- 존재 시 활성화 및 비활성화
- 존재X 시 비밀번호 설정화면으로 이동

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|비밀번호 존재x 시 |<img src = "https://user-images.githubusercontent.com/86879099/209777591-2156c78f-dad9-428c-afef-b907cf26bfdd.gif" width = 200 height = 380>|

2022-12-28 11:35 UTC, jaeryo2357 requested changes
짱짱 수고많았어요!!

2022-12-28 11:35 UTC, jaeryo2357 commented on domain/src/main/java/com/knocklock/domain/usecase/setting/CheckPasswordSetUseCase.kt
> +    suspend operator fun invoke() = userRepository.checkPasswordSet()
이 부분 혹시 필드를 추가하는 것이 아닌 password가 empty인지 여부를 체크하는 식으로 변경하는건 어떤가요? 👀

2022-12-28 11:35 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
> +                navigateByUserSettings = { navController.navigate(NavigationRoute.SettingGraph.Password.route) },
혹시 navigateByUserSettings 람다 내부에서 추후 다른곳으로 이동할 여지가 있을까요??

있다면 매개변수로 Route 이름을 전달받거나 
```suggestion
                navigateByUserSettings = { route ->
                   navController.navigate(route )
                },
```
없다면 네이밍을 수정하면 좋을 것 같아요!
```suggestion
                navigateToPasswordInputScreen= { navController.navigate(NavigationRoute.SettingGraph.Password.route) },
```

2022-12-29 03:51 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
> +                navigateByUserSettings = { navController.navigate(NavigationRoute.SettingGraph.Password.route) },
위에 민욱이의 navigateToPasswordInputScreen 네이밍이 더 명확하게 보입니당

2022-12-29 03:51 UTC, 014967 approved these changes
고생했어용

2022-12-29 08:44 UTC, KimHance commented on domain/src/main/java/com/knocklock/domain/usecase/setting/CheckPasswordSetUseCase.kt
> +    suspend operator fun invoke() = userRepository.checkPasswordSet()
생각해보니 굳이 따로 체크하지 않고 empty인지만 검사해도 될 것 같네요

2022-12-29 08:45 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
> +                navigateByUserSettings = { navController.navigate(NavigationRoute.SettingGraph.Password.route) },
반영했습니다!

2022-12-29 13:03 UTC, jaeryo2357 approved these changes
:) 굳

2022-12-29 13:03 UTC, merged