Feature/disable home key action
Knock-Lock/Knock-Lock pull request #69
Opened 2023-01-05 07:30 UTC by 014967

## 🔥 관련 이슈

close #30 

## 🔥 PR Point

- 상태바 제어( 접근성 서비스(api 31이상) 및 reflection 사용)
- HomeWatcher(System bar listener)
- NotificationListener 에서 composeView 윈도우 등록
- ComposeView와 window layout params 관련 로직 별도 클래스로 생성
- 잠금 해제 바 추가 

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|잠금 화면 |https://user-images.githubusercontent.com/62296097/210725072-31696b1e-6d76-4037-92ad-74cf0e48f4fe.mp4 |

클래스가 무거워지는 것을 막으려고 별도 클래스로 빼거나 했는데, 위치가 이상할수도 있어요 
기존에 Activity는 지우고, NotificationListenerService에서 바로 window에 view를 등록하도록 변경했습니다.
HiltViewModel을 사용할 수 없어서 stateholder에 useCase를 주입했어요
버그는 많을 것으로 예상합니다 ...ㅠ

2023-01-05 07:40 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +
UseCase관련한 로직들은 추후 제거 될 것 같아요.
Listener에서 notification List들을 들고 있고 바로 view에 전달하는 방법이 icon이나, 동기화하는 과정에서 편할 것 같아서
관련한 정보를 찾아보면 좋을 것 같다는 생각이 듭니다

2023-01-05 07:42 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +class InitLockScreenView(
compose View를 WindowManager에 등록하기 위해서는 아래와 같은 로직이 필요했습니다

2023-01-05 07:43 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +        return params
대부분 deprecated된 값들이 많은데, API를 대응해서 별도의 코드로 작성했을 때 동일한 ui 동작을 하지 않더라구요 
ex) systembar hide같은?

2023-01-05 07:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +                        } catch (e: NoSuchMethodException) {
hide되어 접근할 수 없는 로직을 접근하기 위해서 reflection으로 로직을 접근했습니다

2023-01-05 15:15 UTC, jaeryo2357 requested changes
짱짱 진짜 고생많았어요 ㅜㅜ
잔 이슈들은 논 이슈로 넘어가도 될 것 같아요!

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/res/values-v27/themes.xml
> +    <style name="LockScreenActivity">
LockScreenActivity Style을 사용안하고 있는 것 같아요. 지워도 되는 style일까요? 👀

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/Swipeable.kt
> +import androidx.compose.animation.core.Animatable
오우 Swipeable은 라이브러리 느낌으로 생각해서 리뷰는 생각할게요!

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/DismissStatusBarService.kt
> +    }
```suggestion
```
super 그대로 호출하기 때문에 지워도 상관없겠죠?? 👀

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/ComposeLifecycleOwner.kt
> + */
오 좋은글이네요. 그런데 혹시 주석이랑 해당 파일이랑 관련있는 부분이 어디일까요??
lifecycleOwner 주입이 필요하다는 부분일까요?? 👀

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +class BlockStatusBar constructor(
현재 사용하고 있지 않아서 지워도 되는 파일일까요?? 👀

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +}
View라고 네이밍하기는 어색한 것 같아요! `onRemoveComposeViewListener` 처럼 명확히 네이밍하는거 어떤가요?

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +
해당 조건문에 따르면 `Build.VERSION_CODES.N_MR1`보다 작은 버전의 기기에서는 무조건 false가 나올 것 같은데 괜찮을까요??

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            builder.append(this.packageName)
```suggestion
            val package = "package:$packageName"
```
으로 줄일 수 있을 것 같아요!

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +}
👍 좋네요 ㅋㅋㅋ TimeClock이라는 View도 있군요

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/StartApplicationReceiver.kt
> +interface OpenLockScreen {
Callback interface 형태는 Listener로 네이밍을 통일하는 것도 좋아보여요!
```suggestion
interface OnOpenLockScreenListener {
```

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/StartApplicationReceiver.kt
> +    fun start() {
좀 더 명확히 네이밍하면 좋을 것 같아요!!
```suggestion
    fun unregisterReceiver() {
        context.unregisterReceiver(this)
    }

    fun registerReceiver() {
```

2023-01-05 15:15 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +    ControlComposeView {
요즘 느끼고 잇는데 listener를 class 자체에서 구현하고 있고, 게다가 여러가지를 한번에 구현하고 있으면
override 함수들이 어떤 Listener에서 호출되는지 해당 파일에서만 보면 잘 모르겠더라구요.

그래서 생성시점에 object로 구현해서 넣어주는 방식이 좀더 가독성이 있다고 느끼고 있어요. 참고만 해주세요!

2023-01-05 15:27 UTC, 014967 commented on presentation/src/main/res/values-v27/themes.xml
> +    <style name="LockScreenActivity">
Activity를 지워서 삭제해도 될것같아용

2023-01-05 15:27 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/Swipeable.kt
> +import androidx.compose.animation.core.Animatable
네네 그대로 가져온거라 !

2023-01-06 04:02 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/DismissStatusBarService.kt
> +    }
반영할께용

2023-01-06 04:32 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/ComposeLifecycleOwner.kt
> + */
위의 내용은 ComponentActivity에서 전체화면 컴포저블을 만드는 방법을 기억하고 싶어서 링크를 적어뒀어용

2023-01-06 04:35 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/ComposeLifecycleOwner.kt
> + */
https://stackoverflow.com/questions/64585547/jetpack-compose-crash-when-adding-view-to-window-manager
https://gist.github.com/handstandsam/6ecff2f39da72c0b38c07aa80bbb5a2f

위의 LifecycleOwner 관련한 내용은 위의 두내용을 참고했습니당

2023-01-06 04:36 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/ComposeLifecycleOwner.kt
> + */
ComposeView는 LifecycleOwner가 필요한데 없어서 직접 생성해서 주입해야한다는 내용이예욥 !
주석으로 달린 링크보다 방금 올린 링크가 더 적합할 것 같아용

2023-01-06 04:37 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +class BlockStatusBar constructor(
구현은 했지만, 추후에 사용할지도 몰라서 남겨두는 게 좋을 것 같다는 생각인데 어떻게 생각하시나요?

2023-01-06 04:37 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +}
네이밍이 가장 어려웠던 것 같아요 
comment 달아주는 네이밍이 더 명확하네요 반영할께용

2023-01-06 04:38 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/ComposeLifecycleOwner.kt
> + */
위의 주석은 지우도록 할께영

2023-01-06 04:40 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +}
@jaeryo2357 OnRemove라고 명시보다, 나중에 추가적인 기능들이 들어갈 수 있을것 같아서 
OnComposeViewListener라고 수정으로 수정할께용

2023-01-06 04:43 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +
`Build.VERSION_CODES.N_MR1`는 API 25를 의미하는데, 25이상부터 Overlay권한을 받아야하고 그 이하는 안받아도 됩니당!

2023-01-06 04:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            builder.append(this.packageName)
넹넹반영할께용

2023-01-06 04:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +}
일단 넣어놓은 건데 더 이쁜 View는 추후 피처에서 추가할께용

2023-01-06 04:45 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/StartApplicationReceiver.kt
> +interface OpenLockScreen {
네네  Listener로 통일화할께용

2023-01-06 04:50 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/StartApplicationReceiver.kt
> +    fun start() {
Receiver 클래스들의 method를 위와 동일하게 전부 변경했습니당

2023-01-06 05:01 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +    ControlComposeView {
이번에 구현하면서 저도 동일하게 느끼고 있던 부분이였어용
비교해보니까 가독성은 확실히 좋아지는 것 같습니다

좋은 방법인것같아용

2023-01-06 05:35 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +    ControlComposeView {
@jaeryo2357 [bd51538](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/bd51538e6dcf8b36f4e8242d43242414c83769e9)  반영했습니당


추가로 window Size를 얻는 부분에서 deprecated된 코드를 버전별로 분기했습니다

2023-01-06 05:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/StartApplicationReceiver.kt
> +    fun start() {
@jaeryo2357  [2b3fe7d](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/2b3fe7dec11fea11c2c863e30ac3e8f89990cb10)
[6a665e8](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/6a665e8a3ecce6e49d481a7c75e133be02c63c9d) 에서 반영했습니당

2023-01-06 05:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/StartApplicationReceiver.kt
> +interface OpenLockScreen {
@jaeryo2357  [2b3fe7d](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/2b3fe7dec11fea11c2c863e30ac3e8f89990cb10)
[6a665e8](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/6a665e8a3ecce6e49d481a7c75e133be02c63c9d) 에서 반영했습니당

2023-01-06 05:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +}
@jaeryo2357  [2b3fe7d](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/2b3fe7dec11fea11c2c863e30ac3e8f89990cb10)
[6a665e8](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/6a665e8a3ecce6e49d481a7c75e133be02c63c9d) 에서 반영했습니당

2023-01-06 05:45 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/ComposeLifecycleOwner.kt
> + */
@jaeryo2357  [d3851f6](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/d3851f6eec577c5aeec647f48df713ba868ee86b) 반영했습니다

2023-01-06 05:45 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            builder.append(this.packageName)
@jaeryo2357 [bd51538](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/bd51538e6dcf8b36f4e8242d43242414c83769e9)에서 반영했습니당

2023-01-06 14:31 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +class BlockStatusBar constructor(
개인적인 입장에서는 현재 사용하지 않다면 지우는 것이 맞는 것 같아요!
- 지금 시점에서는 커밋에 해당 파일이 들어가 있기 때문에 추후 필요하다면 커밋으로부터 클래스 복원 가능!
- 리뷰어 입장에서는 해당 클래스 파일을 현재 적용하고 있지 않아 리뷰하기 애매 (추후 삭제될 파일이면 비효율이기 때문)
@014967

2023-01-06 14:45 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +
아아 그렇군요!! 넵

2023-01-08 06:36 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +class BlockStatusBar constructor(
@jaeryo2357 커밋에 남아있기때문에 괜찮을꺼같네용 삭제할께용~

2023-01-08 06:41 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +class BlockStatusBar constructor(
@jaeryo2357 상태바 제어를 api 버전에 따라서 BlockStatusBar, DismissStatusBarService 로 구현했는데 두개 다 지우도록 하고 나중에 필요시에 넣는 것으로 할께요

2023-01-08 06:46 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/BlockStatusBar.kt
> +class BlockStatusBar constructor(
@014967 [1afbbe1](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/1afbbe15e6dd60803320cdf03ba2590289d8dc84) 반영했습니다~~

2023-01-08 06:46 UTC, 014967 commented on presentation/src/main/res/values-v27/themes.xml
> +    <style name="LockScreenActivity">
@jaeryo2357 [afa2634](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/afa263481a907df8e5a55ce908bf1f052916c6ab) 반영했습니당

2023-01-08 07:42 UTC, KimHance reviewed
이게 형을 2주간 괴롭힌 그 피처군요ㅠㅠ 고생하셨습니다.😭
모르는게 너무 많아서 궁금한거랑  별거 아니지만  스코프 ..함수 .. 제안드립니다 ㅎ..

2023-01-08 07:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/MainActivity.kt
>                          Toast.makeText(this@MainActivity, "권한이 허용되었습니다.", Toast.LENGTH_SHORT).show()
Toast가 여러곳에서 반복 사용되는것 같아서 
 ```kotlin
 // MainActivity에서만 사용되는 경우
private fun showToastMessage(message: String) {
   Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
}
// Toplevel함수
fun showToastMessage(context: Context, message: String) {
    Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
}
```
처럼 함수로 분리해서 사용하면 어떠나용

2023-01-08 07:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/SystemBarEventReceiver.kt
> +        override fun onReceive(context: Context, intent: Intent) {
inner class로 사용된 이유가 있나요??

2023-01-08 07:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +        lifecycleOwner.handleLifecycleEvent(Lifecycle.Event.ON_CREATE)
스코프 함수를 쓰는게 어떤..읍읍

2023-01-08 07:42 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            intent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)
```suggestion
           val intent = Intent("android.settings.action.MANAGE_OVERLAY_PERMISSION", Uri.parse(builder.toString())).apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)
            }
```
스코프 함ㅅ.. 어때요..ㅎㅎ?

2023-01-08 07:54 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/SystemBarEventReceiver.kt
> +        override fun onReceive(context: Context, intent: Intent) {
이런 이전에는 다른 이름이였는데, 상위를 BroadcastReceiver로 변경할께용

2023-01-08 08:04 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/MainActivity.kt
>                          Toast.makeText(this@MainActivity, "권한이 허용되었습니다.", Toast.LENGTH_SHORT).show()
따로 util 패키지에 만들어놓을께영

2023-01-08 08:08 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/receiver/SystemBarEventReceiver.kt
> +        override fun onReceive(context: Context, intent: Intent) {
@KimHance [a7752c5](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/a7752c50d4f6e40c891938ce6236cf673a1ce076) 반영했습니당

2023-01-08 08:08 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            intent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)
@KimHance [c70e610](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/c70e610cbc4c528b04f968e12b21040ca51231a6) 적용했습니당

2023-01-08 08:09 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +        lifecycleOwner.handleLifecycleEvent(Lifecycle.Event.ON_CREATE)
@KimHance [c70e610](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/c70e610cbc4c528b04f968e12b21040ca51231a6) 적용했습니당

2023-01-08 08:09 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/MainActivity.kt
>                          Toast.makeText(this@MainActivity, "권한이 허용되었습니다.", Toast.LENGTH_SHORT).show()
@KimHance [a6955e0](https://github.com/Knock-Lock/Knock-Lock/pull/69/commits/a6955e050a21bb8b009c81b4b9324889a8df8073) 생성했습니당

2023-01-08 08:19 UTC, KimHance approved these changes
진짜 너무너무너무너무x100 고생하셨습니다. 민욱이형의 리뷰는 다 검토 못해봤지만 제 수준에서는 aprrove 하겠습니다.

2023-01-08 09:43 UTC, jaeryo2357 approved these changes
수고했어요!! apporve 가시죠

2023-01-08 10:37 UTC, merged