[feat]: 시계위젯 구현
Knock-Lock/Knock-Lock pull request #73
Opened 2023-01-17 15:44 UTC by KimHance

## 🔥 관련 이슈

close #72 #21

## 🔥 PR Point

- 시계 위젯 구현
- dateformat은 한국어만 고려하였습니다.
- TextClock을 사용하였습니다.
- 크기와 색상은 현재 고정이며 확장성을 고려한 방향도 고려중
- 가로(시간, 시간+초), 세로(시간) 3가지 타입 구현

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|위젯 미리보|<img src = "https://user-images.githubusercontent.com/86879099/212943336-67e03bc6-0547-4265-8618-4d2cc55b3658.png" width = 120 height =250>|

2023-01-17 15:45 UTC, KimHance commented
뭔가 이쁘게 더 만들어보고 싶었는데 AndroidView로 사용하다 보니 제약이 많아서 기본 3개만 구현하였습니다.
잽싸게 선택하는 컴포저블을 만들어보겠습니당

2023-01-18 16:14 UTC, jaeryo2357 requested changes
UI 이쁘네요! 수고하셨어요

2023-01-18 16:14 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/util/TimeFormat.kt
> +    val dateFormat: String = "MM월 dd일 E요일"
월 일 요일도 format으로 표현할 수 있어요!
다국어 지원을 고려해 format으로 지정하면 좋을 것 같아요

https://formestory.tistory.com/6

2023-01-18 16:14 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/widget/Clock.kt
> +            })
Composable에 timeFormat이 변경되면 AndroidView도 업데이트 되어야 하니 update 람다를 구현해야 할 것 같아요!
아래 minute이랑 date clock도 부탁드려요~!

```suggestion
         AndroidView(
            factory = { context ->
                TextClock(context).apply {
                    format12Hour = timeFormat.timeFormat
                    textSize = 36F
                    setTextColor(Color.WHITE)
                }
            },
            update = { textClock ->
                textClock.format12Hour = timeFormat.timeFormat
            }
        )
```

2023-01-19 05:50 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/util/TimeFormat.kt
> +    val dateFormat: String = "MM월 dd일 E요일"
요런것까진 몰랐는데 확인하고 반영하겠습니다!

2023-01-19 05:51 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/widget/Clock.kt
> +            })
update 람다라는게 있군요. 반영하겠습니다 ^^

2023-01-19 09:19 UTC, 014967 approved these changes
이쁘게 잘 구현했는데영? 
고생했습니다

2023-01-19 12:35 UTC, jaeryo2357 approved these changes
굳 :) 확인했어요

2023-01-19 12:35 UTC, merged