Feature/refactor get notification
Knock-Lock/Knock-Lock pull request #75
Opened 2023-01-20 06:16 UTC by 014967

## 🔥 관련 이슈

close #74 

## 🔥 PR Point

- notification 저장을 Room에서 Stateholder가 직접 들고 있는 것으로 변경
- Notification에 아이콘과 앱 네임 추가 
- Usecase, mapper, repository, Room data base 관련 로직 제거

## issue 
- notification 에 대한 동일한 key가 오는 경우
(ex : 동일한 채팅방에서 생성되는 메시지 )
- 기존에 있던 메시지가 갱신됨
-> 메시징 그룹핑과 함께 unique key를 전달하도록하려함 ( next feature)

2023-01-20 14:30 UTC, jaeryo2357 approved these changes
로직 부분은 확인완료했어요 :)

2023-01-20 14:30 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                    }
```suggestion
                    val date = Date(statusBarNotification.postTime)
                     val stringPostTime = try {
                              SimpleDateFormat("a HH:mm", Locale.KOREA).format(date)
                          } catch (e: Exception) {
                              ""
                          }
```

오전 오후도 시간 포맷으로 나타낼 수 있을 것 같아요!

2023-01-20 14:30 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            notificationScope.launch {
여기서 코루틴 Job이 최초로 생성되는 것 같은데
이후 작업에서 Main Thread에서 실행되어야 하기 때문에 수정이 필요할 듯 하네요. (근본적인 이유는 모르겠네요 ㅠ)
```suggestion
            notificationScope.launch(Dispatchers.Main) {
```

2023-01-20 14:30 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            notificationScope.launch {
```suggestion
           notificationScope.launch(Dispatchers.Main) {
```

2023-01-21 05:47 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            notificationScope.launch {
@jaeryo2357 [8de8579](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/8de8579639f450f0078fa7658edef67851e734c6)

View가 초기화 되는 시점을 MainThread로 변경했습니당

2023-01-21 05:47 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/LockScreenNotificationListener.kt
> +            notificationScope.launch {
@jaeryo2357 [8de8579](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/8de8579639f450f0078fa7658edef67851e734c6)

View가 초기화 되는 시점을 MainThread로 변경했습니당

2023-01-21 06:06 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                    }
@jaeryo2357 이런 꿀기능이 있었네영 [b2ddc67](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/b2ddc67d201a44f3000540d56d3370b2dd1d100e)추가했습니다

2023-01-23 05:33 UTC, KimHance approved these changes
고생하셨습니당 ^^
해피 설 이에요~

2023-01-23 05:33 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                    }
```suggestion
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                        applicationInfo = runCatching {
                            packageManager.getApplicationInfo(
                                packageName,
                                PackageManager.ApplicationInfoFlags.of(PackageManager.GET_META_DATA.toLong())
                            )
                        }.onSuccess {
                            appTitle =
                                packageManager.getApplicationLabel(it).toString()
                        }.getOrNull()
                    } else {
                        applicationInfo = runCatching {
                            packageManager.getApplicationInfo(packageName, 0)
                        }.onSuccess {
                            appTitle =
                                packageManager.getApplicationLabel(it).toString()
                        }.getOrNull()
                    }
```
application이 성공일 때도 null이 들어올 수 있다면  기본 코드로 유지해도 되겠지만, 그게 아니라면 분기를 줄이고 가독성 면에서 runCatching을 추천드립니다!

2023-01-23 08:30 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                    }
@KimHance 맛있네요 반영해볼께요

2023-01-25 08:53 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +                    }
@KimHance [eded568](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/eded56836f8a493fc42847e89e954180ea16edab) 반영했습니다

2023-01-25 13:10 UTC, KimHance approved these changes
리뷰 반영하시느라 수고하셨습니다🫡

2023-01-25 13:10 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +    notificationList: ImmutableList<Pair<Triple<String, String, String>, List<Notification>>>,
ㅗㅜㅑ.... 이게 최선이겠죠 ㅠㅠ?

2023-01-25 13:10 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +            }
쌓여있는 효과군용 👍

2023-01-25 13:10 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +            notificationList = notificationArray.asSequence()
오 시퀀스 짞짞👍

2023-01-25 13:37 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +    notificationList: ImmutableList<Pair<Triple<String, String, String>, List<Notification>>>,
@KimHance 흠 key를 데이터클래스로 만들어줘서 넣는 방법도 있는데, 그게 아니라면 triple밖에 없네영

2023-01-26 12:30 UTC, jaeryo2357 requested changes
확인했습니다!!

2023-01-26 12:30 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +    val notification = notificationList[0]
notifcation List가 Empty일수도 있어서 한번 size를 체크해줘도 좋을 것 같아요!
```koltin
  if (notificationList.isEmpty()) return
```

2023-01-26 12:30 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +    ) {}
```suggestion
 val moreNotificationShape = RoundedCornerShape(bottomStart = 5.dp, bottomEnd = 5.dp)
 Row(
        modifier = modifier.background(
            color = Color(0xFFFAFAFA).copy(alpha = 0.9f),
            shape = moreNotificationShape
            )
            .clip(shape = moreNotificationShape )
    ) {}
```

같은 shpae를 쓴다는 의미도 좋고 가독성도 좋아져서 변수화를 해도 좋을 것 같아요!

2023-01-26 12:30 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +    notificationList: ImmutableList<Pair<Triple<String, String, String>, List<Notification>>>,
엇 음.. 데이터 클래스로 하는것이 좋을 것 같아요!

2023-01-27 06:09 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +    val notification = notificationList[0]
@jaeryo2357  NotificationList는 최소 한개가 들어가게 됩니다

2023-01-27 06:15 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreen.kt
> +    notificationList: ImmutableList<Pair<Triple<String, String, String>, List<Notification>>>,
@jaeryo2357  @KimHance  [b80a751](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/b80a751e67cb3ac7496ccfed49bc0526ad41249e) 반영했습니다

2023-01-27 06:15 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +    ) {}
@jaeryo2357 [a63cff8](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/a63cff80d0bd1a23d6036192457f0c9702a0851f) 반영햇습니다

2023-01-29 08:06 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +    val notification = notificationList[0]
아아 네네 로직적으로는 그렇게 되지만 매개변수 자체에서 empty List를 거를수 없어서 emptyList를 넘길경우 exception으로 죽는 Composable라고 생각되어서요!

2023-01-29 08:16 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenNotiItem.kt
> +    val notification = notificationList[0]
@jaeryo2357 이해했습니당 [2fbbc88](https://github.com/Knock-Lock/Knock-Lock/pull/75/commits/2fbbc88a0d78f4fca1bee8a2bce67810a5d9425c) 반영했어용

2023-01-29 08:48 UTC, merged