Feature/connect update pass word
Knock-Lock/Knock-Lock pull request #86
Opened 2023-02-22 07:36 UTC by 014967

## 🔥 관련 이슈

close #85 

## 🔥 PR Point
```kotlin
-            when (state) {
            when (passwordInputState) {
                is PasswordInputState.PasswordNoneState -> {
-                    checkPasswordNoneState(state)
                    checkPasswordNoneState(passwordInputState as PasswordInputState.PasswordNoneState)
                }
                is PasswordInputState.PasswordConfirmState -> {
-                    checkPasswordConfirmState(state)
                    checkPasswordConfirmState(passwordInputState as PasswordInputState.PasswordConfirmState)
```
기존에는 
```kotlin
passwordInputState = when (state) {
            is PasswordInputState.PasswordNoneState -> {
                state.copy(inputPassword = state.inputPassword + newPasswordNumber)
            }
            is PasswordInputState.PasswordConfirmState -> {
                state.copy(inputPassword = state.inputPassword + newPasswordNumber)
            }
        }
```
state를 copy한 값에 더해도 passwordInputState가 업데이트 되기 떄문에 when 안에 state를 넣으면 가장 최근 값이 갱신이 되지않는 값이 넘어오게 되어있었습니다.

대신 스마트 캐스팅이 되지 않네영

2023-02-22 11:19 UTC, jaeryo2357 approved these changes
수고했습니다 :)

2023-02-22 11:19 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
>          if (state.inputPassword.length + 1 >= MAX_PASSWORD_LENGTH) {
```suggestion
        if (passwordInputState.inputPassword.length >= MAX_PASSWORD_LENGTH) {
```

싱크 맞추려면 이 변수도 `passwordInputState`로 해주면 더 좋겠네요 :0

2023-02-22 11:20 UTC, jaeryo2357 requested changes
확인부탁드립니다...!

2023-02-22 11:20 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
> +                updatePasswordUseCase(state.savedPassword)
아..! 그런데 이곳은 비밀번호 업데이트가 아닌 체크를 하는 곳이어서
DataStore에 값을 저장하는 로직은 없어야 하는 것 같아요!

update 대신 DataStore에서 비밀번호 가져오는 로직만 있어도 되지않을까요??

2023-02-22 13:27 UTC, KimHance requested changes
비밀번호 가져오는 로직이 있으면 좋을 것 같네용

2023-02-22 13:27 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
> +                updatePasswordUseCase(state.savedPassword)
이부분은 저도 동의합니다!

2023-02-23 12:40 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
> +                updatePasswordUseCase(state.savedPassword)
@jaeryo2357 DataStore에서 값을 가져오는 로직은 현재 구현된 것은 없졍?

2023-02-23 14:45 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
> +                updatePasswordUseCase(state.savedPassword)
`[GetUserUseCase.kt](https://github.com/Knock-Lock/Knock-Lock/blob/feature/connectUpdatePassWord/domain/src/main/java/com/knocklock/domain/usecase/setting/GetUserUseCase.kt)`
사용하면 될것같아요!

2023-02-24 06:46 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
> +                updatePasswordUseCase(state.savedPassword)
@jaeryo2357 @KimHance  비밀번호 업데이트를 하는 적절한 위치가 여기라고 생각했는데 혹시 더 적절한 곳이 있을까? 비밀번호를 업데이트를 하는 곳이 없는 것 같아서 혹시 따로 만들어야하는 건지 궁금해 , **나는 usecase만 연결해야지라는 투두만 생각하고 작업을 한거라** 명확한 작업범위를 몰라서 ,,,

지금은 기존에 저장되어있는 비밀번호를 비교하는 로직이 필요한지 잘모르겠엉
비밀번호 변경을 할 때 기존에 저장되어있던 비밀번호를 입력하고 비밀번호를 변경하도록 구현되어있는 것 같지가 않아서 
현재는 비밀번호 변경 -> 잠금 설정을 위한 비밀번호 입력( 아마 새로운 비밀번호겠지 ? ) -> 입력한 비밀번호 다시 한번 더 입력
으로 구현되어있어서 어느 부분에서 기존의 저장된 비밀번호를 비교해야하지?라는 궁금증이 생겼으

현재는 비밀번호를 잠금 스크린에서 입력하고 들어왔다는 가정으로 설계되어 기존의 비밀번호를 입력할 필요없이, 바로 비밀번호를 변경가능하도록 구현되어있는거 아닌가 해서

2023-02-24 13:03 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/setting/password/PasswordInputViewModel.kt
>          if (state.inputPassword.length + 1 >= MAX_PASSWORD_LENGTH) {
@jaeryo2357 [ace5662](https://github.com/Knock-Lock/Knock-Lock/pull/86/commits/ace566204805dbe9552e721a34418cac977e0c10) 반영했어영

2023-02-24 13:08 UTC, jaeryo2357 approved these changes
죄송합니다 ㅎ,,, 👍

2023-02-24 13:08 UTC, KimHance approved these changes
💪

2023-02-24 13:27 UTC, merged