Refactor/change index 6 -> 5
Knock-Lock/Knock-Lock pull request #88
Opened 2023-02-22 07:40 UTC by 014967

## 🔥 관련 이슈

close #87 

## 🔥 PR Point
- 비밀 번호 비교할때 인덱스가 5일때 비교를 해야해서 수정합니다.

2023-02-22 11:26 UTC, jaeryo2357 requested changes
의견 부탁드립니다 :)

2023-02-22 11:26 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/password/PassWordScreenStateHolder.kt
> +            if (insertPassWordIndex == 5) {
전체적으로 마지막 인덱스를 가지고 로직 처리하는 곳이 많아서 상수로 정의해도 좋을 것 같아요!
사실 비밀번호 길이에 대한 부분은 이 부분 뿐만 아니라 설정에서 비밀번호 입력하는 화면에도 의존성이 있기 때문에 루트 폴더에 상수를 정의해도 좋을 것 같네요?

```kotlin
 // PasswordConstant.kt
 
 const val MAX_PASSWORD_LENGTH = 6
```

위처럼 정의가 되고 이 코드에서 해당 상수로 로직 처리를 한다면 추후 비밀번호가 늘어나거나 줄어들었을 때 유지보수가 쉬울 것 같아요

```diff
val passWordState = mutableStateListOf<PassWord>().apply {
-        repeat(6) {
+       repeat(MAX_PASSWORD_LENGTH) {
            add(PassWord(""))
        }
    }
    ...
     fun updatePassWordState(passWord: String) {
-        if (insertPassWordIndex <= 5) {
+       if (insertPassWordIndex <= MAX_PASSWORD_LENGTH) {
            passWordState[insertPassWordIndex] = passWordState[insertPassWordIndex].copy(number = passWord)
-            if (insertPassWordIndex != 5) {
+           if (insertPassWordIndex != MAX_PASSWORD_LENGTH) {
                insertPassWordIndex += 1
            }
-            removePassWordIndex = if (insertPassWordIndex == 5) {
+            removePassWordIndex = if (insertPassWordIndex == MAX_PASSWORD_LENGTH) {
                insertPassWordIndex
```

이번 이슈랑 어느정도 관련있어보여서 추천드렸습니다 :)

2023-02-22 13:28 UTC, KimHance reviewed
그..그렇다고 하네요 ??👀

2023-02-22 13:30 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/password/PassWordScreenStateHolder.kt
> +            if (insertPassWordIndex == 5) {
@jaeryo2357 아직 제가 센스가 너무 없네요  확실히 정의해두는게 너무나 좋은데 ㅠㅠ 반영하겠습니다

2023-02-24 06:50 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/password/PassWordScreenStateHolder.kt
> +            if (insertPassWordIndex == 5) {
@jaeryo2357 이부분은 있다 회의때 다시 한번 질문하겠습니다

2023-02-25 11:12 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/password/PassWordScreenStateHolder.kt
> +            if (insertPassWordIndex == 5) {
@jaeryo2357 [6e28104](https://github.com/Knock-Lock/Knock-Lock/pull/88/commits/6e2810474d19cfc9a4398f111b9ede4afb2660ea) 반영했습니다

2023-02-25 15:00 UTC, jaeryo2357 approved these changes
확인했습니다 :)

2023-02-26 06:04 UTC, merged