[feat]: #22 홈 배경설정하기
Knock-Lock/Knock-Lock pull request #91
Opened 2023-02-22 14:07 UTC by KimHance

## 🔥 관련 이슈

close #22 

## 🔥 PR Point

- 갤러리의 사진을 가져와 배경설정
- 뷰모델에 임시 배경
- 처음엔 세팅된 배경을 가져오고 이후 설정 전까지 임시 배경값으로 화면이 변화도미

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|초기 기본 배경화면|<img src = "https://user-images.githubusercontent.com/86879099/220642604-30b786e2-80b9-4d86-b8bc-a978b0140d33.png" width = 125 height = 250>|
|임시 배경화면| <img width=125 height = 250 src="https://user-images.githubusercontent.com/86879099/220643463-c7e6af21-b033-4f12-81e8-ce3b20ac1a56.png">|

## 🤕 TODO
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{98aab25 18794:com.knocklock/u0a169} (pid=18794, uid=10169) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
현재 이와 같은 에러가 떠서 퍼미션에서 막히고 있습니다 ㅠㅠ
첫 변경에는 잘 적용되나 한번 변경 이후엔 퍼미션에서 터지고 있네요ㅠㅠ 
Draft로 올리겠습니다ㅠ

2023-02-23 14:43 UTC, jaeryo2357 requested changes
메모리가 낮은 기기에서는 이미지가 너무 커서 죽네요 ㅜㅜ
해결 방법으로는

1. Bitmap 메모리 처리가 필요할 것 같아요... 해상도에 맞춰서 Bitmap을 압축하는 방법이에요.
그런데 Recomposition 환경에서 여러번 처리되지 않도록 신경써야할 것 같아요.

2. 어차피 지금 로컬에 저장하는 이미지라서 해상도별로 이미지를 다양하게 저장해야할 것 같네요

![image](https://user-images.githubusercontent.com/33657541/220939282-3053ce9c-4e75-4859-9308-1001839fba45.png)

2023-02-23 14:43 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +            }
추후 이미지 뿐만 아니라 시계 타입등이 변경되면
Custom이지만 background는 Default일수도 있을 것 같아요.
그래서 체크를 안전하게 하면 좋을 것 같네요

```suggestion
            if (value is TmpScreenState.Custom) {
                saveWallPaperUseCase((value.screen.background as?LockScreenBackground.LocalImage).imageUri ?: return)
            }
```

2023-02-23 14:43 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/util/Extensions.kt
> +    }
```suggestion
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) { 
            val source = ImageDecoder.createSource(resolver, this)
            ImageDecoder.decodeBitmap(source)
        } else {
            MediaStore.Images.Media.getBitmap(resolver, this)
        }
```

if문으로 해도 될 것 같아요! ㅋㅋㅋㅋ

2023-02-23 14:43 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/home/HomeScreen.kt
> +                            .asImageBitmap()
ㅠㅠ ㅜ Compose라 확신이 없네요.
이미지 라이브러리에서는 캐싱처리를 해줄 것 같은데... 이렇게 직접 Bitmap 만들어주는 리컴포지션 환경에서 괜찮을까요.

직접 설치해서 확인해보니 리컴포지션이 안되긴 하네요

2023-02-23 14:43 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
> +            ).apply {
👍 Compose에서 Luancher는 이렇게 쓰는군요.

2023-02-24 08:24 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/home/HomeScreen.kt
> +                            .asImageBitmap()
coil 사용으로 변경했습니당. 다시 확인 부탁드릴게요

2023-02-24 08:25 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/util/Extensions.kt
> +    }
coil사용으로 삭제 되었습니다!

2023-02-24 08:26 UTC, KimHance commented on presentation/src/main/java/com/knocklock/presentation/home/HomeViewModel.kt
> +            }
거기까진 생각 못했네요. 감사합니다 :)

2023-02-24 13:26 UTC, jaeryo2357 approved these changes
확인했어요!

2023-02-24 13:38 UTC, merged