[Feature] : 저장된 배경화면 연결하기
Knock-Lock/Knock-Lock pull request #95
Opened 2023-02-27 09:11 UTC by 014967

## 🔥 관련 이슈

close #94

## 🔥 PR Point

- 저장된 이미지를 string으로 coil로 로드를 할 때, 
  java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
  와 같은 exception이 발생합니다.
  
- https://nanamare.tistory.com/170 위의 글을 보고서 allocator를 software로 변경하였습니다.

- context.grantUriPermission(context.packageName, this, Intent.FLAG_GRANT_READ_URI_PERMISSION)을 통해 내부 갤러리 파일의 bitmap을 가져오는 권한을 허용합니다.

- R.drawable로 가져오는 Drawable를 Bitmap으로 변경했습니다. 동일한 exception발생하기 때문에

## 📷 Screenshot
|기능|스크린샷|
|:---|---|
|기능A 구현|<img src = "" width = 400>|
|기능B 구현||
|...||

2023-02-27 09:15 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/DecodeBitmap.kt
> +}
@jaeryo2357 @KimHance Drawable을 그대로 전달해도 글에서 설명한 exception이 동일하게 발생하더라구요.. Bitmap으로 변경해줘서 넣어주니 오류는 사라졌으나 이유를 모르겠습니다

2023-02-27 09:23 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/DecodeBitmap.kt
> +}
@jaeryo2357 @KimHance 오류에 대한 근본적인 해결책은 아닌것같아 .. 걱정이 되는 부분이라 쫌더 찾아봐야할 것 같아요

https://github.com/coil-kt/coil/issues/159

위의 글을 보고 allowHardware(false)를 추가하니 bitmap변환 로직이 없어도 동작합니다

2023-02-27 09:26 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/DecodeBitmap.kt
> +}
If you're rendering on a software only canvas, you'll need to add allowHardware(false) to your request. 

Canvas로만 렌더링을 한다면 allowHardware(false)를 추가해야한다고 합니다

2023-02-27 09:27 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/util/DecodeBitmap.kt
> +}
Compose로만 Screen을 구현해서 일까요?

2023-02-27 12:31 UTC, jaeryo2357 requested changes
수고하셧습니다~!

2023-02-27 12:31 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +    val context: Context,
```suggestion
    private val context: Context,
```

private로 해도 될 것 같아요!

2023-02-27 12:31 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +
혹시 background만 아닌  LockScreen 그대로 observe field로 하는건 어때요??
추후 LockScreen에 시계 타입등의 field가 추가되면 현재 구조는 수정이 필요할 것 같아요!

2023-02-27 12:31 UTC, jaeryo2357 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +            )
좋네요! HomeScreen 코드에서 중복코드가 많이 없어졌네요!! :)
그런데 HomeScreen이랑 LockScreen이랑 동일한 UI를 그리지만 참조하는 Composable이 달라 중복 코드가 늘어날 것 같아요. 같이 고민해야할 부분같네요

2023-02-27 12:38 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +
@jaeryo2357 아 정확합니다 시계도 들어온다는 것을 잊고 있었네용 그렇게 수정하도록할께요  😍

2023-02-27 12:45 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +    val context: Context,
@jaeryo2357 기존처럼 다시 변경했습니다 [5bf2eaf](https://github.com/Knock-Lock/Knock-Lock/pull/95/commits/5bf2eaf88e73c2a0ec0f7b7ad72098cb78bab70b)

2023-02-27 12:55 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/service/InitLockScreenView.kt
> +            )
@jaeryo2357 맞아요 배경같은 경우도 중복코드라고 할 수 있겠네용, 나중에 시계가 추가된다면 그것두 포함되겠군영?

2023-03-01 06:04 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
>                              vm.saveTmpWallPaper(uri.toString())
https://github.com/coil-kt/coil/issues/1345
카톡에서 보여드린 경고 로그는 이 이슈밖에 찾지 못했어요
여기서 제공하는 해결책으로도 해결은 되지 않네요 ㅠ

2023-03-01 06:09 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/navigation/KnockLockNavHost.kt
>                              vm.saveTmpWallPaper(uri.toString())
위의  코드는 Uri Permission 관련은 
https://commonsware.com/blog/2020/08/08/uri-access-lifetime-still-shorter-than-you-might-think.html
의 글을 참고했습니다.

데이터 베이스에 콘텐츠의 복사본을 만들지 않는 이상, 기본적으로 Uri의 접근이 영구적으로 가능한것이 아닌가봐요,
Intent.FLAG_GRANT_READ_URI_PERMISSION의 권한을 Persistable( 지속적인 ) 으로 주어서 , 지속적인 액세스가 가능하도록 합니다.

2023-03-03 08:44 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +
@jaeryo2357 [b32ea7b](https://github.com/Knock-Lock/Knock-Lock/pull/95/commits/b32ea7bba43dda00942693b65a33f4232dd82317) 수정했습니당

2023-03-03 08:47 UTC, 014967 commented on presentation/src/main/java/com/knocklock/presentation/lockscreen/LockScreenStateHolder.kt
> +
@jaeryo2357 type cast 수정되었습니다. [ea0188a](https://github.com/Knock-Lock/Knock-Lock/pull/95/commits/ea0188a581b054504d0cef7138897e9434b9ed10)

2023-03-03 08:54 UTC, merged